[workspace]
channels = ["conda-forge"]
name = "attribution_tutorial"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
xarray = ">=2026.1.0,<2027"
numpy = ">=2.4.2,<3"
xesmf = ">=0.9.2,<0.10"
pandas = ">=3.0.0,<4"
geopandas = ">=1.1.2,<2"
exactextract = ">=0.3.0,<0.4"
ipykernel = ">=7.1.0,<8"
h5netcdf = ">=1.8.1,<2"
netcdf4 = ">=1.7.4,<2"
gdown = ">=5.2.1,<6"
cfunits = ">=3.3.7,<4"
cf-units = ">=3.3.1,<4"
